# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobloggen < Formula
  desc "Unopinionated static site generator for markdown-based blogs"
  homepage "https://github.com/harrydayexe/GoBlog"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.2.6/GoBlog_0.2.6_Darwin_x86_64.tar.gz"
      sha256 "d801e88716b1b08ba9a5c5f5264e31c2ddc13f316e6491c76f94fb615c4b1f88"

      def install
        bin.install "gobloggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.2.6/GoBlog_0.2.6_Darwin_arm64.tar.gz"
      sha256 "6e1cb84007c9fb31e02fe186dcfe9bd4edd740245ac3a0123a68d004d99ab668"

      def install
        bin.install "gobloggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.2.6/GoBlog_0.2.6_Linux_x86_64.tar.gz"
      sha256 "7ff352992d2a048ba45ebb2abe8e3fa1ad9e03eaed90e026646f0170c63aedab"
      def install
        bin.install "gobloggen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.2.6/GoBlog_0.2.6_Linux_arm64.tar.gz"
      sha256 "b8a874d963c7ec13c3d6f3c6a0514bb8005e9fc66512c767a2a5ef07627eaec6"
      def install
        bin.install "gobloggen"
      end
    end
  end

  test do
    system "#{bin}/gobloggen", "-help"
  end
end
