# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobloggen < Formula
  desc "Unopinionated static site generator for markdown-based blogs"
  homepage "https://github.com/harrydayexe/GoBlog"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.6.0/GoBlog_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "a31e66252aa98d9917b8ab2d53bbcd0633d4e82e00e97fd876610629c08720a7"

      def install
        bin.install "gobloggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.6.0/GoBlog_0.6.0_Darwin_arm64.tar.gz"
      sha256 "d2b542061292837e1874d9cf6344407830c800286e2f85928636b6b4234ce972"

      def install
        bin.install "gobloggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.6.0/GoBlog_0.6.0_Linux_x86_64.tar.gz"
      sha256 "c4d9fa76b20dfde149ac292b716f267ef36de87b624bd1151dd3fe2759ca8abe"
      def install
        bin.install "gobloggen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.6.0/GoBlog_0.6.0_Linux_arm64.tar.gz"
      sha256 "3e219e980bb38010ccd94b91107d9e4bfe0f53b1007a7cb479bc05848d693dc0"
      def install
        bin.install "gobloggen"
      end
    end
  end

  test do
    system "#{bin}/gobloggen", "-help"
  end
end
