# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobloggen < Formula
  desc "Unopinionated static site generator for markdown-based blogs"
  homepage "https://github.com/harrydayexe/GoBlog"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.5.0/GoBlog_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "47aad52bed5ee432f049b209c8c7b2dd83ad57db77b6e05f9a519803e08942b2"

      def install
        bin.install "gobloggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.5.0/GoBlog_0.5.0_Darwin_arm64.tar.gz"
      sha256 "e32e270c110eaf774467c41bc091813b50c586006d9e2d9f2971e62c5c415858"

      def install
        bin.install "gobloggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.5.0/GoBlog_0.5.0_Linux_x86_64.tar.gz"
      sha256 "4cc9d808dff5adadbf9e4c1d8ddcf9d2adb6cd8cbf25b74d08c13165dff6a91f"
      def install
        bin.install "gobloggen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harrydayexe/GoBlog/releases/download/v0.5.0/GoBlog_0.5.0_Linux_arm64.tar.gz"
      sha256 "cefee84f7f799adc9bc04fbeccfe95597c0564137b5c3b6548333cbfa7f32cf8"
      def install
        bin.install "gobloggen"
      end
    end
  end

  test do
    system "#{bin}/gobloggen", "-help"
  end
end
